### ISSUE TITLE
[Error] Inference error: TensorArray has size zero, but element shape [?,200] 

### ISSUE THREAD

**Issue by moonsh** [cifkao/groove2groove#10]
I think training is succeded somehow. There was no error during training.
And.. I just tested it with the midi files you showed on the demo web page.
Two input (content input, style input) 

However, I get the below two errors. I think one is from rnn layers and not sure for the other one.

2021-04-23 22:51:39 seonghyeon-cbim tensorflow[53024] INFO Restoring parameters from experiments/v01/latest.ckpt-9600
2021-04-23 22:51:39 seonghyeon-cbim museflow[53024] INFO Variables restored from experiments/v01/latest.ckpt-9600
16it [00:00, 33.97it/s]
Traceback (most recent call last):
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
**tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,200] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.**
	 [[{{node encoder_rnn/rnn/TensorArrayStack/TensorArrayGatherV3}} = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=[?,200], _device="/job:localhost/replica:0/task:0/device:CPU:0"](encoder_rnn/rnn/TensorArray, encoder_rnn/rnn/TensorArrayStack/range, encoder_rnn/rnn/while/Exit_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/groove2groove/models/roll2seq_style_transfer.py", line 407, in <module>
    main()
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/groove2groove/models/roll2seq_style_transfer.py", line 401, in main
    args.func(experiment, args)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/groove2groove/models/roll2seq_style_transfer.py", line 185, in run_midi
    sequences = self._run_cli(args, pipeline)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/groove2groove/models/roll2seq_style_transfer.py", line 197, in _run_cli
    sample=args.sample, softmax_temperature=args.softmax_temperature)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/groove2groove/models/roll2seq_style_transfer.py", line 211, in run
    self.trainer.session, dataset, sample, softmax_temperature, options=options) or []
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/groove2groove/models/roll2seq_style_transfer.py", line 122, in run
    options=options)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/museflow/model_utils.py", line 170, in run_over_dataset
    options=options))
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/museflow/model_utils.py", line 139, in run
    return session.run(fetches, feed_dict, options=options)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,200] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node encoder_rnn/rnn/TensorArrayStack/TensorArrayGatherV3 (defined at /home/seonghyeon/anaconda3/envs/groove2groove/lib/python3.6/site-packages/museflow/components/rnn_layer.py:47)  = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=[?,200], _device="/job:localhost/replica:0/task:0/device:CPU:0"](encoder_rnn/rnn/TensorArray, encoder_rnn/rnn/TensorArrayStack/range, encoder_rnn/rnn/while/Exit_2)]]**

**Comment by moonsh** [comment]
I found the error is from an input midi file. The input midi file should contain notes properly.

By the way, I tested with CUDA 11.0. It's working.
