### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by PapayasTehSkeletor** [cifkao/groove2groove#8]
I'm getting this message always when I try to use the demo. What's happening?
![image](https://user-images.githubusercontent.com/47577184/115058846-13e8db80-9ebc-11eb-892d-833a09f50c91.png)

**Comment by cifkao** [comment]
I'm not sure, the demo seems to be working on my examples. Could you share your input files?

**Comment by PapayasTehSkeletor** [comment]
[Content and Style.zip](https://github.com/cifkao/groove2groove/files/6329572/Content.and.Style.zip)

Thank you in advance for the help!

**Comment by PapayasTehSkeletor** [comment]
> [Content and Style.zip](https://github.com/cifkao/groove2groove/files/6329572/Content.and.Style.zip)
> 
> Thank you in advance for the help!

Oh... I just tried using other midis. Got a weird error with some of them but it worked with others, then I edited the style midi I sent and now its working. I don't know exactly why it didn't worked before.

**Comment by cifkao** [comment]
I tried your inputs and got this (there are hundreds of these warnings, showing just a few):
```
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.115385, end 0.115385. New start 0.230769, end 0.230769.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.115385, end 0.115385. New start 0.230769, end 0.230769.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.115385, end 0.115385. New start 0.230769, end 0.230769.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.115385, end 0.115385. New start 0.230769, end 0.230769.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.317308, end 0.317308. New start 0.634615, end 0.634615.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.423077, end 0.423077. New start 0.846154, end 0.846154.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.423077, end 0.423077. New start 0.846154, end 0.846154.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.519231, end 0.519231. New start 1.038462, end 1.038462.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.519231, end 0.519231. New start 1.038462, end 1.038462.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.519231, end 0.519231. New start 1.038462, end 1.038462.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.519231, end 0.519231. New start 1.038462, end 1.038462.
WARNING:absl:Skipping note that ends before or at the same time it begins. Original start: 0.730769, end 0.730769. New start 1.461538, end 1.461538.
...

/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/museflow/note_sequence_utils.py:88: RuntimeWarning: 602 notes skipped in adjust_notesequence_times
  warnings.warn(f'{skipped_notes} notes skipped in adjust_notesequence_times', RuntimeWarning)
ERROR:app:Exception on /api/v1/style_transfer/v01_drums/ [POST]
Traceback (most recent call last):
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/flask_limiter/extension.py", line 702, in __inner
    return obj(*a, **k)
  File "/home/ocifka/projects/groove2groove/api/app/__init__.py", line 101, in run_model
    output_seq = pipeline.postprocess(outputs)
  File "/home/ocifka/venv/groove2groove/lib/python3.6/site-packages/groove2groove/io.py", line 261, in postprocess
    raise RuntimeError(f'Expected {len(self._durations)} sequences, got {len(sequences)}')
RuntimeError: Expected 10 sequences, got 0
```

So I suspect that your style input consists of very short or zero-duration notes, which are skipped by the pre-processing code, so the model gets an empty input.

**Comment by cifkao** [comment]
@PapayasTehSkeletor BTW, the tempo of your style input seems to be off as well.

**Comment by PapayasTehSkeletor** [comment]
Wtf...? Well, that's probably because the midi was generated using musenet. Musenet has a really weird format.

**Comment by PapayasTehSkeletor** [comment]
> Wtf...? Well, that's probably because the midi was generated using musenet. Musenet has a really weird format.

But I think the problem is solved now that I know this. Thank you sir!

**Comment by cifkao** [comment]
> Wtf...? Well, that's probably because the midi was generated using musenet. Musenet has a really weird format.

Ah, that would explain it. I guess MuseNet measures time in seconds, while Groove2Groove requires accurate metrical timing information.

**Comment by MeenakshiSirigiraju** [comment]
Getting below error
![image](https://user-images.githubusercontent.com/111839156/229045328-e4ccf826-c352-4167-b5c4-becf1bfd1616.png)

Below are the files that I have tried,
[files.zip](https://github.com/cifkao/groove2groove/files/11119020/files.zip)

**Comment by cifkao** [comment]
@MeenakshiSirigiraju Just tested and it works for me. Maybe the server was temporarily down or you were experiencing connection issues on your side?

**Comment by MeenakshiSirigiraju** [comment]
@cifkao It worked fine for the sample files provided on the website but not for custom inputs, so I don't think the issue is from my side.

**Comment by cifkao** [comment]
@MeenakshiSirigiraju I tried with your inputs and it did work for me. Could you try again and see if it works now?

**Comment by MeenakshiSirigiraju** [comment]
@cifkao I tried it's not working still giving the same error.
